-- AlterTable
ALTER TABLE "AlienPart" ADD COLUMN     "raidTimeBoost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "starBoost" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "xpBoost" INTEGER NOT NULL DEFAULT 0;
